### ISSUE TITLE
ERROR: JAVA_HOME is set to an invalid directory: /opt/java/openjdk

### ISSUE THREAD

**Issue by dellisd** [alvr/alpine-android#11]
The CI I have set up that uses this docker image suddenly stopped working and it appears to be related to the newest release.

This was using `alvrme/alpine-android:android-30-jdk11`:

```
Images used:
    build : docker.io/alvrme/alpine-android@sha256:c39202e4da263bb66bfc65a49bdba941f97bebc91c7ca9d48617fccb0b97acc8
```

```
+ ./gradlew ktlintCheck --no-parallel

ERROR: JAVA_HOME is set to an invalid directory: /opt/java/openjdk

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

**Comment by alvr** [comment]
Hi @dellisd, I will take a look tomorrow. Meanwhile use the previous tag `android-30-jdk11-v2021.06.09`.

**Comment by alvr** [comment]
Hi @dellisd, I was not able to reproduce it on my machine.

![image](https://user-images.githubusercontent.com/217315/125838425-de25b040-9885-42a0-95f0-dac9c7c5437f.png)
![building](https://user-images.githubusercontent.com/217315/125838426-b3e9ec22-ca3c-47df-b064-f77f7a2656b5.png)

It seems to be working using the latest version. Could you try again running the same command or another, like `./gradlew check` or `./gradlew build`. If the problem persists and the repo is public, post the link to the repo or upload a sample data with the same Gradle configuration otherwise.

This is also weird because the only change between versions is the Android 31 SDK.

**Comment by dellisd** [comment]
Unfortunately the project isn't public so there isn't much I can share there, however I did run a build on a separate project that is open source, [but the build worked normally](https://github.com/cuhacking/atlas/runs/3080496217).

Both the `ktlintCheck` and `test` commands failed with the same error.

Reverting to the previous tag did resolve the issue, so it does seem related to the latest image but I can't think of any reason why, especially as you say the only difference was the version of the SDK. This is running in a Bitbucket Pipeline, so perhaps that's related.

**Comment by nayaksushma** [comment]
Like @dellisd said, even my CI pipeline failed with the same error.
```ERROR: JAVA_HOME is set to an invalid directory: /opt/java/openjdk```

Reverting to previous tag resolved the issue.

**Comment by alvr** [comment]
Hi @dellisd, @nayaksushma, @darekxan. Tomorrow I will create a test image using [Liberica JDK](https://bell-sw.com/pages/libericajdk/) instead of AdoptOpenJDK because of #10. I will let you know when it is ready so you can test this version.

**Comment by daviCalavera** [comment]
Hi, I have the same error using: `alvrme/alpine-android:android-31` and  `alvrme/alpine-android:android-30`
The strange thing is that if I use the image locally I have no problem, only through the CI.

**Comment by edwnmrtnz** [comment]
> Hi, I have the same error using: `alvrme/alpine-android:android-31` and `alvrme/alpine-android:android-30`
> The strange thing is that if I use the image locally I have no problem, only through the CI.

That must because you have a JAVA_HOME environment variable set to jdk11 already or you have configured your AS to use jdk11.

**Comment by alvr** [comment]
I published a new version for AdoptOpenJDK `alvrme/alpine-android:android-30-jdk11-v2021.08.01`, aswell as one based on Liberica `alvrme/alpine-android-liberica:android-30-jdk11-v2021.08.01`. Please, try this two, and tell me if it works.

Thanks.

**Comment by dellisd** [comment]
Gave the two new images a try today. The AdoptOpenJDK one failed with the same error, but the Liberica one ran normally.

**Comment by 20100** [comment]
As a workaround, I set the JAVA_HOME to "". The Gradle wrapper does no more fails with the invalid directory : /opt/java/openjdk.
If it can help.

**Comment by stefanoberdoerfer** [comment]
I'm still experiencing this issue with image: `android-31-jdk11-v2022.01.01`.
I wanted to upgrade from `android-30-jdk11-v2021.05.05` (which is working) to android 31 and got this error message:
`ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/jdk-11.0.13-bellsoft-x86_64`

After adding `export JAVA_HOME=""` to my CI-script (like @20100 mentioned) the error changed to a font error again which I experienced in the past. Eventhough I'm already manually installing fonts via `apk add --no-cache freetype fontconfig ttf-dejavu` (also mentioned here: https://github.com/usefulness/easylauncher-gradle-plugin/issues/201).
Very strange.

Nevertheless I was able to get my build to work by using this older android-31 image: `android-31-jdk11-v2021.08.01`
